language: perl
perl:
    - 5.10

env:
    - V_OPENRESTY=1.9.15.1
install:
    - cpanm -v --notest Test::Nginx
before_script:
    - sudo apt-get update -q
    - sudo apt-get install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev -y
    - sudo apt-get install make build-essential lua5.1 -y
    - wget https://openresty.org/download/openresty-$V_OPENRESTY.tar.gz
    - tar xzf openresty-$V_OPENRESTY.tar.gz
    - cd openresty-$V_OPENRESTY && ./configure && make && sudo make install && cd ..
script:
    - export PATH=/usr/local/openresty/nginx/sbin:$PATH
    - cp lib/resty/ctxdump.lua /usr/local/openresty/lualib/resty/
    - prove -r t/
